version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    shm_size: 2g
    command: /bin/sh -c "rm -f /dokode/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dokode
    ports:
      - "3000:3000"
    depends_on:
      - db

